language: node_js
node_js:
- node
notifications:
  email:
    on_success: always
    on_failure: always
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: it@my-ideas.it
  api_key:
    secure: htQgMGftjAA6IO1nwOYDv9o73Vw1PO5pIqZ9SUweS4tp4qwphmQulR/Su8poEza9mZmxrgtaAgjAWQ+vtBthH9HhZ19aYFFxPQnUqsv6RlRoAhHl4DJpm6MxKZa2VjetI3o0WEICRz4aHx0jFyUiPucqiKTmhhyPAdd260TI1lMjXTmFLe5kJKykfH40Cs0EJhyJFDUQ1IUYoc+NkojhKlWzKzhsyegAZemNi1gJvGtsY65QGMIrSvJQsCHcU2L2WeR1gaFBsn3AHtXcg/cTy5g3ieL84GIlk8h12XQE4k7R7UuGGqlQE7YW7rmTkqierxuA8n+ygwq0fZOtrTGtqe/ilFA+9zS+Qyiz/yxBZEPcOGdgWDbJzOlOLoT/ueEOL2jlYdXS5IXAUJXcGuyLafwZuTmV/bhP1gR+za1SqGOdOCMRBkUUzwtMP+mtHca8UhXW73W8m+rulhv2iIZeyjs/7Ol3/ynCyevyMMOvQGyo1N9Tunen+pmo52Pv1JIbxbRTHfQblPhlSDCIi3UrgkOuuHlafIDPq5iTiJyKifY7nmazj6jJRjLXEI4E1WxH8++NWHOFfrPPyfSYoe+wCuwIUG36YM/u6cV5Zt/Dk09lKlgDXW+pw8dBla3nXugBFXpdObgSCO2air2qURSKdtwEYDybUGKa+l9VsBBfjxE=
